﻿// This file was auto-generated by ML.NET Model Builder. 
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.ML.Data;
using Microsoft.ML.Trainers.FastTree;
using Microsoft.ML.Trainers;
using Microsoft.ML.Transforms;
using Microsoft.ML;

namespace CollegeScorePredictor
{
    public partial class NoDefense
    {
        /// <summary>
        /// Retrains model using the pipeline generated as part of the training process. For more information on how to load data, see aka.ms/loaddata.
        /// </summary>
        /// <param name="mlContext"></param>
        /// <param name="trainData"></param>
        /// <returns></returns>
        public static ITransformer RetrainPipeline(MLContext mlContext, IDataView trainData)
        {
            var pipeline = BuildPipeline(mlContext);
            var model = pipeline.Fit(trainData);

            return model;
        }

        /// <summary>
        /// build the pipeline that is used from model builder. Use this function to retrain model.
        /// </summary>
        /// <param name="mlContext"></param>
        /// <returns></returns>
        public static IEstimator<ITransformer> BuildPipeline(MLContext mlContext)
        {
            // Data process configuration with pipeline data transformations
            var pipeline = mlContext.Transforms.Categorical.OneHotEncoding(new []{new InputOutputColumnPair(@"IsConference", @"IsConference"),new InputOutputColumnPair(@"IsNeutralSite", @"IsNeutralSite")}, outputKind: OneHotEncodingEstimator.OutputKind.Indicator)      
                                    .Append(mlContext.Transforms.ReplaceMissingValues(new []{new InputOutputColumnPair(@"Week", @"Week"),new InputOutputColumnPair(@"Year", @"Year"),new InputOutputColumnPair(@"TeamConference", @"TeamConference"),new InputOutputColumnPair(@"TeamFirstDowns", @"TeamFirstDowns"),new InputOutputColumnPair(@"TeamTotalYards", @"TeamTotalYards"),new InputOutputColumnPair(@"TeamNetPassingYards", @"TeamNetPassingYards"),new InputOutputColumnPair(@"TeamYardsPerPass", @"TeamYardsPerPass"),new InputOutputColumnPair(@"TeamPassingAttempts", @"TeamPassingAttempts"),new InputOutputColumnPair(@"TeamRushingYards", @"TeamRushingYards"),new InputOutputColumnPair(@"TeamRushingAttempts", @"TeamRushingAttempts"),new InputOutputColumnPair(@"TeamYardsPerRushAttempt", @"TeamYardsPerRushAttempt"),new InputOutputColumnPair(@"TeamFieldGoals", @"TeamFieldGoals"),new InputOutputColumnPair(@"TeamPointsPerPlay", @"TeamPointsPerPlay"),new InputOutputColumnPair(@"OpponentConference", @"OpponentConference"),new InputOutputColumnPair(@"TeamTurnoverMargin", @"TeamTurnoverMargin"),new InputOutputColumnPair(@"OpponentTurnoverMargin", @"OpponentTurnoverMargin")}))      
                                    .Append(mlContext.Transforms.Concatenate(@"Features", new []{@"IsConference",@"IsNeutralSite",@"Week",@"Year",@"TeamConference",@"TeamFirstDowns",@"TeamTotalYards",@"TeamNetPassingYards",@"TeamYardsPerPass",@"TeamPassingAttempts",@"TeamRushingYards",@"TeamRushingAttempts",@"TeamYardsPerRushAttempt",@"TeamFieldGoals",@"TeamPointsPerPlay",@"OpponentConference",@"TeamTurnoverMargin",@"OpponentTurnoverMargin"}))      
                                    .Append(mlContext.Regression.Trainers.FastTree(new FastTreeRegressionTrainer.Options(){NumberOfLeaves=4,MinimumExampleCountPerLeaf=126,NumberOfTrees=576,MaximumBinCountPerFeature=1022,FeatureFraction=0.99999999,LearningRate=0.0597806878782174,LabelColumnName=@"TeamScore",FeatureColumnName=@"Features"}));

            return pipeline;
        }
    }
}
